#!/bin/sh
# /etc/init.d/power-monitor
### BEGIN INIT INFO
# Provides:          power-monitor
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO
case "$1" in
	start)
		echo "Starting power monitor..."
		gpio edge 1 falling
		python /root/power/monitor.py &
		;;
	stop)
		echo "Stopping power monitor..."
		kill `ps -ef | grep monitor.py | grep -v grep | awk '{print $2}'`
		killall gpio-new
		;;
	*)
		echo "Usage: /etc/init.d/power-monitor (start|stop)"
		exit 1
		;;
esac

exit 0
